# Generated by Django 5.1 on 2024-12-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='idx_sale_date'),
        ),
    ]
